### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ECNUHP** [lancopku/Graph-to-seq-comment-generation#7]
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    main()
  File "train.py", line 291, in main
    max_bleu = train(model, vocab, dataloader, scheduler, optim, updates)
  File "train.py", line 118, in train
    outputs = model(batch, use_cuda)
  File "/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 93, in forward
    contexts, state, attns = self.encode(src, src_mask, concept, concept_mask, title_index, adjs)
  File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 71, in encode
    return contexts, state, attn
UnboundLocalError: local variable 'attn' referenced before assignment

出现上述错误是因为什么呢？
跪求解答

**Comment by astrodrew** [comment]
同问，而且“segged_content.txt”是如何获得的

**Comment by AbnerCode** [comment]
可以通过从json文件中抽取

**Comment by shenjian5** [comment]
> Traceback (most recent call last):
> File "train.py", line 299, in
> main()
> File "train.py", line 291, in main
> max_bleu = train(model, vocab, dataloader, scheduler, optim, updates)
> File "train.py", line 118, in train
> outputs = model(batch, use_cuda)
> File "/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 93, in forward
> contexts, state, attns = self.encode(src, src_mask, concept, concept_mask, title_index, adjs)
> File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 71, in encode
> return contexts, state, attn
> UnboundLocalError: local variable 'attn' referenced before assignment
> 
> 出现上述错误是因为什么呢？
> 跪求解答


需要预先定义一下，大概是代码中漏定义了。
    def encode(self, contents, contents_mask, concepts, concept_mask, title_index, adjs):
        contexts = []
        states = []
        attn=[]
   ……

**Comment by liweitj47** [comment]
attn可以直接删去，这个是分析的时候看attention 权重的发自我的华为手机-------- 原始邮件 --------主题：Re: [lancopku/Graph-to-seq-comment-generation] run error (#7)发件人：shenjian5 收件人：lancopku/Graph-to-seq-comment-generation 抄送：Subscribed 



Traceback (most recent call last):

File "train.py", line 299, in

main()

File "train.py", line 291, in main

max_bleu = train(model, vocab, dataloader, scheduler, optim, updates)

File "train.py", line 118, in train

outputs = model(batch, use_cuda)

File "/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in call

result = self.forward(*input, **kwargs)

File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 93, in forward

contexts, state, attns = self.encode(src, src_mask, concept, concept_mask, title_index, adjs)

File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 71, in encode

return contexts, state, attn

UnboundLocalError: local variable 'attn' referenced before assignment

出现上述错误是因为什么呢？

跪求解答



需要预先定义一下，大概是代码中漏定义了。



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/lancopku/Graph-to-seq-comment-generation/issues/7#issuecomment-660855293",

"url": "https://github.com/lancopku/Graph-to-seq-comment-generation/issues/7#issuecomment-660855293",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by shenjian5** [comment]
> 可以通过从json文件中抽取



“segged_content.txt”的内容格式，能否指点一下呢？

**Comment by shenjian5** [comment]
> attn可以直接删去，这个是分析的时候看attention 权重的发自我的华为手机-------- 原始邮件 --------主题：Re: [lancopku/Graph-to-seq-comment-generation] run error (#7)发件人：shenjian5 收件人：lancopku/Graph-to-seq-comment-generation 抄送：Subscribed Traceback (most recent call last): File "train.py", line 299, in main() File "train.py", line 291, in main max_bleu = train(model, vocab, dataloader, scheduler, optim, updates) File "train.py", line 118, in train outputs = model(batch, use_cuda) File "/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in call result = self.forward(*input, **kwargs) File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 93, in forward contexts, state, attns = self.encode(src, src_mask, concept, concept_mask, title_index, adjs) File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 71, in encode return contexts, state, attn UnboundLocalError: local variable 'attn' referenced before assignment 出现上述错误是因为什么呢？ 跪求解答 需要预先定义一下，大概是代码中漏定义了。 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#7 (comment)](https://github.com/lancopku/Graph-to-seq-comment-generation/issues/7#issuecomment-660855293)", "url": "[#7 (comment)](https://github.com/lancopku/Graph-to-seq-comment-generation/issues/7#issuecomment-660855293)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]


另外“segged_content.txt”的内容格式，能否指点一下呢？

**Comment by shenjian5** [comment]
“segged_content.txt”的内容格式，能否指点一下呢？ 能给https://github.com/lancopku/Graph-to-seq-comment-generation这项目写个详细一些的readme吗？另外能告知一下Python, PyTorch and CUDA version吗？谢谢。



另外基于之前的项目，再结合一下文章Keywords-Guided Abstractive Sentence Summarization（https://zhuanlan.zhihu.com/p/133610392），有可能可以再往前更进一步（即：多文档结合指定的关键字和来生成摘要内容），或者结合一下AMR的内容。
















在 2020-07-20 15:40:25，"李炜" <notifications@github.com> 写道：

attn可以直接删去，这个是分析的时候看attention 权重的发自我的华为手机-------- 原始邮件 --------主题：Re: [lancopku/Graph-to-seq-comment-generation] run error (#7)发件人：shenjian5 收件人：lancopku/Graph-to-seq-comment-generation 抄送：Subscribed

Traceback (most recent call last):
File "train.py", line 299, in
main()
File "train.py", line 291, in main
max_bleu = train(model, vocab, dataloader, scheduler, optim, updates)
File "train.py", line 118, in train
outputs = model(batch, use_cuda)
File "/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 93, in forward
contexts, state, attns = self.encode(src, src_mask, concept, concept_mask, title_index, adjs)
File "/opt/lang.huo/mybot/question_generation/models/graph2seq.py", line 71, in encode
return contexts, state, attn
UnboundLocalError: local variable 'attn' referenced before assignment
出现上述错误是因为什么呢？
跪求解答

需要预先定义一下，大概是代码中漏定义了。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lancopku/Graph-to-seq-comment-generation/issues/7#issuecomment-660855293",
"url": "https://github.com/lancopku/Graph-to-seq-comment-generation/issues/7#issuecomment-660855293",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
